import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import MainLayout from "@/src/layout/MainLayout";
import WalletConnectionProvider from "@/src/provider/WalletConnectionProvider";
import { AutoConnectProvider } from "@/src/provider/AutoConnectProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <WalletConnectionProvider>
          <AutoConnectProvider>
            <AntdRegistry>{children}</AntdRegistry>
          </AutoConnectProvider>
        </WalletConnectionProvider>
      </body>
    </html>
  );
}
